### ISSUE TITLE
Error in test.py

### ISSUE THREAD

**Issue by alondhe** [UTHealth-CCB/covid19_testnorm#1]
Hi all,

I am trying to run the test step, but encounter this error. I did install the dependencies. 

```
  File "test.py", line 3, in <module>
    from TestNorm.covid19_test_norm import load_rules_data, get_loinc_codes
ImportError: No module named TestNorm.covid19_test_norm
```

Any ideas? I'm a Python noob, so probably a novice mistake :) 

Thanks,
Ajit

**Comment by huaxu7000** [comment]
Ajit - Thanks for testing it out. I will ask the developer to take a look immediately. Meanwhile, you can try the online demo for immediate use of the tool: https://clamp.uth.edu/covid/loinc.php. Thanks.

**Comment by LiJianfu2008** [comment]
Hi Ajit,
Thanks for your testing. Can you briefly describe your test env (os, using IDE like pycharm/vs code, etc.)? From my side, I test it with git clone to local path, then install the dependency and run 'python test.py' directly and it works. 
Sometimes when you do some edits and transfer between different os and there may be errors, or more hints may be found in https://stackoverflow.com/questions/338768/python-error-importerror-no-module-named. 
Thanks.

**Comment by alondhe** [comment]
Hi @LiJianfu2008,

Never mind -- it was because I was using the default Python in Mac, which is 2.7. Using 3 resolves the issue.

Thanks!
